language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install cov-core
  - pip install nose2
  - pip install coveralls
script: 
  - nose2
after_success:
  coveralls